### ISSUE TITLE
Postconf not working through check_mk 1.2.4

### ISSUE THREAD

**Issue by geekmush** [HeinleinSupport/check_mk#2]
Installed plugin on monitoring server and agent host.  Server finds it in the re-inventory, but when run, the following error is logged in check_mk's debug log:

```
Invalid output from plugin or error in check:
  Check_MK Version: 1.2.4
  Date:             2014-01-04 04:07:54
  Host:             nks-p-mail-000-c.ssn.nks.net
  Service:          Postfix Config
  Check type:       postconf
  Item:             None
  Parameters:       None
  Traceback (most recent call last):
        File "/var/lib/check_mk/precompiled/nks-p-mail-000-c.ssn.nks.net", line 884, in do_all_checks_on_host
          ^@j^F^@|^W^@<83>^A^@^A|^N^@j^F^@|^O^@|^R^@|^U^@|^V^@d^E^@|^D^@f^F^@<83>^A^@^Aq<95>^@W|^L^@d^O^@|^D^@^Vd^P^@j^G^@|
        File "/var/lib/check_mk/precompiled/nks-p-mail-000-c.ssn.nks.net", line 1869, in check_postconf
      TypeError: 'NoneType' object is not iterable

  Agent info:       [['2bounce_notice_recipient', '=', 'postmaster'],
```

Running the "postfix" agent script on the agent's host spits out the postfix configuration as expected.

All other checks through check_mk to the agent seem to be functional.

**Comment by gurubert** [comment]
Closing, too old.
