### ISSUE TITLE
dell_sc_ctlrfan plugin needs default lower value?

### ISSUE THREAD

**Issue by agabellini** [HeinleinSupport/check_mk#36]
Hello,

This plugin return an error:

```python
Traceback (most recent call last):
  File "/omd/sites/nagtism/share/check_mk/modules/check_mk.py", line 4909, in <module>
    exit_status = do_check(hostname, ipaddress, check_types)
  File "/omd/sites/nagtism/share/check_mk/modules/check_mk_base.py", line 1236, in do_check
    do_all_checks_on_host(hostname, ipaddress, only_check_types)
  File "/omd/sites/nagtism/share/check_mk/modules/check_mk_base.py", line 1523, in do_all_checks_on_host
    res = execute_check(checkname, item, params, description, aggrname, address)
  File "/omd/sites/nagtism/share/check_mk/modules/check_mk_base.py", line 1459, in execute_check
    result = sanitize_check_result(check_function(item, params, info), check_uses_snmp(checkname))
  File "/omd/sites/nagtism/local/share/check_mk/checks/dell_sc_ctlrfan", line 39, in check_dell_sc_ctlrfan
    res = check_fan(saveint(line[3]), params)
  File "/omd/sites/nagtism/local/share/check_mk/checks/fan.include", line 32, in check_fan
    warn, crit= params.get("lower", (None, None))
AttributeError: 'NoneType' object has no attribute 'get'
```

Setting default value for lower values solve the problem. This is my patch that contains also the solution for issue #35 (I don't know if my default values are consistent or not)

```diff
--- /omd/sites/nagtism/checks.old/dell_sc_ctlrfan.orig	2018-06-27 13:22:55.809582553 +0200
+++ dell_sc_ctlrfan	2018-06-27 13:32:10.674842726 +0200
@@ -16,6 +16,10 @@
 # to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
 # Boston, MA 02110-1301 USA.
 
+factory_settings["dell_sc_ctlrfan_default_levels"] = {
+    "lower" : (7000, 6000),
+}
+
 def item_dell_sc_ctlrfan(line):
     ctlr, fan = line[0].split('.')
     return "Ctlr %s Fan %s" % (ctlr, fan)
@@ -34,7 +38,7 @@
         if item_dell_sc_ctlrfan(line) == item:
             res = check_fan(saveint(line[3]), params)
             ctlrfan_state = state.get(saveint(line[1]), ('unknown', 3))
-            info_text = "%s, %s RPM, State is %s %s" % (
+            info_text = "%s, %s RPM, State is %s" % (
                 line[2],
                 line[3],
                 ctlrfan_state[0],
@@ -55,4 +59,5 @@
     'snmp_scan_function'    : False, # lambda oid: 'compellent' in oid('.1.3.6.1.2.1.1.1.0').lower() and oid(".1.3.6.1.4.1.674.11000.2000.500.1.2.1.0") != None,
     'group'                 : "hw_fans",
     'includes'              : [ 'fan.include' ],
+    'default_levels_variable':"dell_sc_ctlrfan_default_levels",
 }
```
Andrea

**Comment by agabellini** [comment]
the patch with the right formatting...

```diff
--- /omd/sites/nagtism/checks.old/dell_sc_ctlrfan.orig	2018-06-27 13:22:55.809582553 +0200
+++ dell_sc_ctlrfan	2018-06-27 13:32:10.674842726 +0200
@@ -16,6 +16,10 @@
 # to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
 # Boston, MA 02110-1301 USA.
 
+factory_settings["dell_sc_ctlrfan_default_levels"] = {
+    "lower" : (7000, 6000),
+}
+
 def item_dell_sc_ctlrfan(line):
     ctlr, fan = line[0].split('.')
     return "Ctlr %s Fan %s" % (ctlr, fan)
@@ -34,7 +38,7 @@
         if item_dell_sc_ctlrfan(line) == item:
             res = check_fan(saveint(line[3]), params)
             ctlrfan_state = state.get(saveint(line[1]), ('unknown', 3))
-            info_text = "%s, %s RPM, State is %s %s" % (
+            info_text = "%s, %s RPM, State is %s" % (
                 line[2],
                 line[3],
                 ctlrfan_state[0],
@@ -55,4 +59,5 @@
     'snmp_scan_function'    : False, # lambda oid: 'compellent' in oid('.1.3.6.1.2.1.1.1.0').lower() and oid(".1.3.6.1.4.1.674.11000.2000.500.1.2.1.0") != None,
     'group'                 : "hw_fans",
     'includes'              : [ 'fan.include' ],
+    'default_levels_variable':"dell_sc_ctlrfan_default_levels",
 }
```

**Comment by gurubert** [comment]
Instead of default_levels I just set params = {} if it's None.

**Comment by agabellini** [comment]
> Instead of default_levels I just set params = {} if it's None.

I'm sorry for the delay. I haven't looked at this plugin again until now that I'm upgrading cmk to 2.0...

Your correction genarate again an error... This is a ligth patch:

```diff
--- dell_sc_ctlrfan.orig	2022-05-04 15:45:42.782196273 +0200
+++ dell_sc_ctlrfan	2022-05-04 15:47:12.773102171 +0200
@@ -33,7 +33,7 @@
         3  : ('degraded', 1),
         }
     if not params:
-        params = {}
+        params = { "lower" : (None, None) }
     for line in info:
         if item_dell_sc_ctlrfan(line) == item:
             res = check_fan(saveint(line[3]), params)
```
